set(sources
    lib/lexer/lexer.cpp
    lib/lexer/token.cpp
    lib/ast/ast.cpp
    lib/ast/expr.cpp
    lib/ast/stmt.cpp
    lib/parser/error.cpp
    lib/parser/expr.cpp
    lib/parser/parser.cpp
    lib/parser/reader.cpp
    lib/parser/stmt.cpp
    lib/object/object.cpp
    lib/object/env.cpp
    lib/eval/eval.cpp
    lib/eval/builtin.cpp
)

set(exe_sources
		src/main.cpp
		${sources}
)

set(headers
    include/monkey/lexer/lexer.h
    include/monkey/lexer/token.h
    include/monkey/ast/ast.h
    include/monkey/ast/expr.h
    include/monkey/ast/stmt.h
    include/monkey/parser/error.h
    include/monkey/parser/expr.h
    include/monkey/parser/parser.h
    include/monkey/parser/reader.h
    include/monkey/parser/stmt.h
    include/monkey/object/object.h
    include/monkey/object/env.h
    include/monkey/eval/eval.h
    include/monkey/eval/builtin.h
)

set(test_sources
  src/lexer/lexer_test.cpp
  src/parser/parser_test.cpp
  src/eval/eval_test.cpp
)
